export enum Errors {
  DEFAULT = '',
  CLEAR = 'Unable to clear completed todos',
  LOAD = 'Unable to load todos',
  EMPTY = 'Title should not be empty',
  ADD = 'Unable to add a todo',
  DELETE = 'Unable to delete a todo',
  DELETE_ID = 'Unable to delete a todo with this id',
  UPDATE = 'Unable to update a todo',
  TOGGLE = 'Failed to update the todo. Please try again later.',
  TOGGLE_ALL = 'Failed to toggle all todos. Please try again later.',
  TITLE_EMPTY = 'Title cannot be empty.',
  TODO_LOAD = 'Error loading todos.',
  TODO_ADD = 'Error adding todo.',
  TODO_DELETE = 'Error deleting todo.',
  TODO_UPDATE = 'Error updating todo.',
}
